image:
  file: .gitpod.Dockerfile

vscode:
  extensions: 
    - "ms-azuretools.vscode-docker"
    - hashicorp.hcl

tasks:
- name: docker create network
  command: docker network create opsbox-network 
- name: docker create builder
  command: |
    BUILDER_NAME=opsbox
    if ! $(docker buildx ls |grep -q ${BUILDER_NAME}); then
      docker buildx create --name ${BUILDER_NAME} --use --bootstrap
    fi