version: '2'
services:
  mindskip-xzs:
    build:
      context: .
    restart: always
    container_name: xzs
    image: seanly/test:mindskip-xzs-1
    environment:
      JAVA_OPTS: -Dfile.encoding=utf-8 -Djava.security.egd=file:/dev/./urandom
    command: dev
    volumes:
      - ./config:/data/service/config
    ports:
      - 8080:8080

# networks:
#   default:
#     name: opsbox-network
#     external: true