/*

# oes-template configure

```yaml
config:
  credentials: jenkins-admin
  groovyScript: |
    println("hello")

```
*/

node {
    stage("download cli") {
        // 定义 Jenkins CLI 文件的 URL
        def jenkinsCliUrl = '${JENKINS_URL}/jnlpJars/jenkins-cli.jar'
        sh "curl -o jenkins-cli.jar ${jenkinsCliUrl}"
    }

    stage("run script") {

        withCredentials([
            usernamePassword(credentialsId: "${config.credentials}", passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')
        ]) {
            // Jenkins CLI 命令
            def jenkinsCliCommand = '${SLAVE_JAVA_EXEC} -jar jenkins-cli.jar -s ${JENKINS_URL} -webSocket -auth ${USERNAME}:${PASSWORD}'

            writeFile file: "./__run.groovy", text: "${config.groovyScript}"

            // 执行 Jenkins CLI 命令并传递 Groovy 脚本
            def listCmd = "${jenkinsCliCommand} groovy = < __run.groovy "
            sh(script: listCmd)
        }
    }
}