version: '2'
services:
  mysql:
    container_name: mysql
    image: seanly/dbset:mysql-5.7.35
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_INITDB_SKIP_TZINFO: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: 'jimureport'
      MYSQL_USER: "jimureport_rw"
      MYSQL_PASSWORD: "jimureport_rw@123"
    command:
      - --server-id=1
    volumes:
      - jimureport-db:/var/lib/mysql
      - ./etc/mysql/:/etc/mysql/conf.d
      - ./initdb.d:/initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e "SHOW DATABASES;"
      interval: 3s
      timeout: 1s
      retries: 5

  jimureport:
    build:
      context: .
    restart: always
    container_name: jimureport
    image: seanly/test:jimureport
    environment:
      JAVA_OPTS: -Dfile.encoding=utf-8 -Djava.security.egd=file:/dev/./urandom
    command: prod
    volumes:
      - ./bin:/data/app/bin
      - ./config:/data/app/config
      - jimureport-upload:/data/app/upload
    ports:
      - 8085:8085

volumes:
    jimureport-db:
    jimureport-upload:

networks:
  default:
    name: opsbox-network
    external: true