version: '3'

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=gitlab123
    healthcheck:
      test: pg_isready -U gitlab -h 127.0.0.1
      interval: 5s
    ports:
    - 5432:5432

# volumes:
#     postgres-data: