name: tke-manual-deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  tke-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo "--//INFO: tag: ${TAG_NAME}"
          VERSION=$(echo $GITHUB_REF |sed 's;refs/tags/jenkins-;;')
          if [ "${VERSION}" == "" ]; then
            echo "please select tke-v... tag."
            exit 1
          fi
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}

      - uses: yokawasa/action-setup-kube-tools@v0.11.1
        with:
          setup-tools: |
            kubectl
            helm
            kustomize
          kubectl: '1.29.3'
          helm: '3.11.1'
          kustomize: '5.0.0'